networks:
  dev:

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: horesmi_erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: erppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
        - dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: erpuser
      DB_PASSWORD: erppass
      DB_NAME: horesmi_erp
      NODE_ENV: production
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    command: node app.js
    networks:
        - dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./frontend:/app/frontend
    networks:
        - dev

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    networks:
        - dev

volumes:
  db_data: